// <auto-generated />
namespace _19._10._2017evening.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bindforstudydate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bindforstudydate));
        
        string IMigrationMetadata.Id
        {
            get { return "201710231300314_bind for studydate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
